services:

  frontend:
    environment:
      NODE_ENV: production
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M

  api-gateway:
    environment:
      NODE_ENV: production
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M

  user-service:
    environment:
      ENV: production
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M

  product-service:
    environment:
      NODE_ENV: production
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M

  order-service:
    environment:
      ENV: production
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M