storage:
  dbPath: /home/vibhavkhaneja/MLOps-Training/week2/day5-deployment/nextjs-nodejs-mongodb/mongodb/data/node2
net:
  bindIp: 127.0.0.1
  port: 27018
replication:
  replSetName: rs0
processManagement:
  fork: true
systemLog:
  destination: file
  path: /home/vibhavkhaneja/MLOps-Training/week2/day5-deployment/nextjs-nodejs-mongodb/mongodb/data/node2/mongod.log
  logAppend: true
