services:

  frontend:
    environment:
      NODE_ENV: development

  api-gateway:
    environment:
      NODE_ENV: development

  user-service:
    environment:
      ENV: development

  product-service:
    environment:
      NODE_ENV: development

  order-service:
    environment:
      ENV: development