events {}

http {

  upstream backend {
    server app-blue:3000;

    # server app-green:3000;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://backend;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /health {
      access_log off;
      return 200 "healthy\n";
    }
  }
}