trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageRepository: flask-app
  containerRegistry: acr-connection
  kubernetesServiceConnection: aks-connection

steps:

- script: |
    docker run --privileged --rm tonistiigi/binfmt --install all
  displayName: Set up QEMU for multi-arch builds

- task: Docker@2
  displayName: Build and Push Image
  inputs:
    command: buildAndPush
    repository: $(imageRepository)
    containerRegistry: $(containerRegistry)
    Dockerfile: Azure-Bootcamp/week2/day4/Dockerfile
    buildContext: Azure-Bootcamp/week2/day4
    arguments: --platform linux/amd64,linux/arm64
    tags: |
      $(Build.BuildId)
      latest

- task: Kubernetes@1
  displayName: Deploy to AKS
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: $(kubernetesServiceConnection)
    command: set
    arguments: image deployment/flask-app flask-app=vibhavacrday4.azurecr.io/flask-app:$(Build.BuildId)

- task: Kubernetes@1
  displayName: Verify Rollout
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: $(kubernetesServiceConnection)
    command: rollout
    arguments: status deployment/flask-app