trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: Docker@2
  displayName: Build Docker Image
  inputs:
    command: build
    Dockerfile: Dockerfile
    repository: flask-app
    tags: |
      $(Build.BuildId)