apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "92b8411c-e1b0-4141-9c51-041bb291a946"
    keyvaultName: "kv-vibhav-day6"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: db-password
          objectType: secret
    tenantId: "95912afd-4771-4072-a56b-8ef84e015310"